# Generated by Django 6.0.1 on 2026-05-25 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_cart_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending / Preparing'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('full_name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=20)),
                ('street_address', models.CharField(max_length=255)),
                ('barangay', models.CharField(max_length=100)),
                ('region', models.CharField(default='Region I (Ilocos Region)', max_length=100)),
                ('province', models.CharField(default='Pangasinan', max_length=100)),
                ('city', models.CharField(default='Urdaneta City', max_length=100)),
                ('postal_code', models.CharField(default='2428', max_length=10)),
                ('address_type', models.CharField(choices=[('home', 'Home'), ('office', 'Office')], default='home', max_length=10)),
                ('landmarks', models.CharField(blank=True, max_length=255, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='dashboard.customer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('price_at_purchase', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='dashboard.order')),
            ],
        ),
    ]
