# Generated by Django 6.0.1 on 2026-06-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_order_gcash_number_order_gcash_reference_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('Pending', 'Preparing / Pending'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Unpaid', 'Unpaid / Pending COD'), ('Awaiting Verification', 'Awaiting GCash Verification'), ('Paid', 'Paid'), ('Refunded', 'Refunded')], default='Unpaid', max_length=25),
        ),
    ]
