# Generated by Django 6.0.1 on 2026-06-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_remove_order_status_order_delivery_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_in_stock',
            field=models.BooleanField(default=True, verbose_name='In Stock'),
        ),
    ]
