# Generated by Django 6.0.1 on 2026-05-31 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('details', models.TextField(help_text='Provide greater detail regarding your custom commission request.')),
                ('reference_image', models.ImageField(blank=True, null=True, upload_to='commissions/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
